# Generated by Django 5.1.2 on 2024-12-14 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('sport_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facilities', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='polls.field')),
            ],
        ),
    ]
