# Generated by Django 5.1.2 on 2024-12-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddetail',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fielddetail', to='polls.field'),
        ),
    ]
